services:
  forodb:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:jammy
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=jfk93k2ghro73hfhjs73
      - MYSQL_DATABASE=mdh349sh
      - MYSQL_USER=m6hf63gs
      - MYSQL_PASSWORD=md83ufjdj49t8f739nf834h
    expose:
      - 3306
      - 33060
  forowp:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 6371:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=forodb
      - WORDPRESS_DB_USER=m6hf63gs
      - WORDPRESS_DB_PASSWORD=md83ufjdj49t8f739nf834h
      - WORDPRESS_DB_NAME=mdh349sh
volumes:
  db_data:
  wp_data: